<a href="https://colab.research.google.com/github/gxilly/BasicProg_DataViz65/blob/main/Pandas101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
unit = pd.read_csv('/content/drive/My Drive/BPDV65/opendata_unittype.csv')
unit.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,NaN,28.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...

# ตรวจสอบ Missing (isnull)

In [4]:
unit.isnull()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,False,False,False,False
2,False,False,False,False,False,False,False,True,False,True,...,True,True,True,True,True,True,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,True,True,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42620,False,False,False,False,False,False,False,True,False,True,...,True,False,True,True,True,True,False,False,False,False
42621,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,True,True,False,False,False,False
42622,False,False,False,False,False,False,False,True,False,True,...,False,True,True,True,True,True,False,False,False,False
42623,False,False,False,False,False,False,False,True,False,False,...,True,False,True,True,True,True,False,False,False,False
42624,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,True,True,False,False,False,False

In [5]:
unit.isnull().any() # .any() การเอาค่าความจริงใน column มา or กัน

row_number              False
unittype_id             False
project_id              False
name_th                  True
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa        True
area_usable_min          True
price_min                True
count_airconditioner     True
count_elevator           True
count_floor_internal     True
count_parking            True
count_room_bath          True
count_room_bed           True
count_room_dinning       True
count_room_guest         True
count_room_kitchen       True
count_room_living        True
count_room_maid          True
count_room_storage       True
count_room_utility       True
date_created            False
date_updated            False
source                  False
url_unittype             True
dtype: bool

In [6]:
unit.isnull().all() # .all() การเอาค่าความจริงใน column มา and กัน

row_number              False
unittype_id             False
project_id              False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
area_total_min_wa       False
area_usable_min         False
price_min               False
count_airconditioner    False
count_elevator           True
count_floor_internal    False
count_parking           False
count_room_bath         False
count_room_bed          False
count_room_dinning      False
count_room_guest        False
count_room_kitchen      False
count_room_living       False
count_room_maid         False
count_room_storage      False
count_room_utility      False
date_created            False
date_updated            False
source                  False
url_unittype            False
dtype: bool

unit.isnull().any().any ->?

In [7]:
unit.isnull().any().any()

True

## ลบ missing

missing  -> null, na (not autorized), NaN(not a number)

In [8]:
unit.dropna()

Empty DataFrame
Columns: [row_number, unittype_id, project_id, name_th, propertytype_id, propertytype_name_en, propertytype_name_th, area_total_min_wa, area_usable_min, price_min, count_airconditioner, count_elevator, count_floor_internal, count_parking, count_room_bath, count_room_bed, count_room_dinning, count_room_guest, count_room_kitchen, count_room_living, count_room_maid, count_room_storage, count_room_utility, date_created, date_updated, source, url_unittype]
Index: []

[0 rows x 27 columns]

In [9]:
unit.dropna(axis=1)

,row_number,unittype_id,project_id,propertytype_id,propertytype_name_en,propertytype_name_th,date_created,date_updated,source
0,27501,unittype_9565,project_2446,2,Condo,คอนโด,2021-11-19 18:00:09,2021-11-19 17:44:45,baania
1,28777,unittype_10267,project_3543,20000,Twin house,บ้านแฝด,2022-01-27 14:30:04,2022-01-27 14:22:55,baania
2,28865,unittype_471,project_143,2,Condo,คอนโด,2022-01-14 15:00:10,2022-01-14 14:40:04,baania
3,24988,unittype_19506,project_7766,2,Condo,คอนโด,2020-12-04 10:40:59,2020-10-14 01:06:48,baania
4,38596,unittype_10290,project_3551,3,Townhome,ทาวน์โฮม,2021-11-12 13:30:08,2021-02-03 12:12:54,baania
...,...,...,...,...,...,...,...,...,...
42620,37109,unittype_38508,project_16864,1,Detached House,บ้าน,2021-11-12 13:22:37,2020-10-14 10:05:42,baania
42621,14,unittype_14016,project_5275,1,Detached House,บ้าน,2020-12-04 10:36:32,2020-10-14 00:37:51,baania
42622,41009,617bde1687dd2300149d2195,617bdd47f62011001350de07,3,Townhome,ทาวน์โฮม,2021-11-12 13:34:17,2021-10-29 18:43:09,baania
42623,9333,unittype_37375,project_16389,1,Detached House,บ้าน,2020-12-04 10:42:26,2020-10-14 19:30:46,baania
42624,780,unittype_17011,project_6762,1,Detached House,บ้าน,2021-11-12 13:19:43,2020-10-14 00:41:39,baania

In [10]:
unit.dropna(how='all')

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,NaN,28.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42620,37109,unittype_38508,project_16864,Canola,1,Detached House,บ้าน,NaN,157.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:22:37,2020-10-14 10:05:42,baania,https://baania.com/th/project/อิคอนเนเจอร์-พระ...
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,NaN,223.0,7490000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42622,41009,617bde1687dd2300149d2195,617bdd47f62011001350de07,Grande,3,Townhome,ทาวน์โฮม,NaN,133.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:34:17,2021-10-29 18:43:09,baania,https://baania.com/th/project/เดอะริคโค้-ทาวน์...
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,...,NaN,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,NaN,170.0,3790000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [11]:
unit.dropna(thresh=22)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
11,2452,unittype_8521,project_2906,New Villa Valdivia,1,Detached House,บ้าน,NaN,441.0,36900000.0,...,1.0,1.0,1.0,1.0,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:47,baania,https://baania.com/th/project/แกรนด์-บางกอก-บู...
41,5766,unittype_31346,project_13202,Acacia,1,Detached House,บ้าน,NaN,185.0,9450000.0,...,1.0,1.0,1.0,NaN,1.0,NaN,2022-03-15 16:30:11,2022-03-15 16:22:00,baania,https://baania.com/th/project/88-แลนด์-แอนด์-เ...
42,38678,unittype_27892,project_11388,ทาวน์โฮมสองชั้น,3,Townhome,ทาวน์โฮม,20.3,144.0,2680000.0,...,1.0,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:33:35,2021-07-15 15:22:52,baania,https://baania.com/th/project/เดอะ-เรสซิเด้นท์...
94,35674,unittype_33903,project_14528,ทาวน์โฮมสองชั้น Type A,3,Townhome,ทาวน์โฮม,21.0,130.0,2000000.0,...,1.0,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:27:19,2021-01-07 10:37:11,baania,https://baania.com/th/project/เดอะ-ไนน์-แอท-ปร...
101,34592,unittype_20435,project_8011,Penthouse,2,Condo,คอนโด,NaN,116.0,21000000.0,...,1.0,1.0,1.0,1.0,1.0,NaN,2022-05-19 12:00:10,2022-05-19 11:33:29,baania,https://baania.com/th/project/อินเตอร์-ลักส์-พ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42503,30946,unittype_10670,project_3705,HBB3,1,Detached House,บ้าน,NaN,217.0,7960000.0,...,1.0,1.0,1.0,1.0,NaN,NaN,2021-11-12 13:19:40,2020-10-14 00:40:15,baania,https://baania.com/th/project/ฮาบิเทีย-ราชพฤกษ...
42524,4811,unittype_3960,project_1261,Amplio-CM,1,Detached House,บ้าน,NaN,184.0,11990000.0,...,1.0,1.0,NaN,NaN,1.0,NaN,2022-02-07 15:30:06,2022-02-07 15:19:43,baania,https://baania.com/th/project/สีวลี-ศรีเวียง-เ...
42541,4636,unittype_30403,project_9963,ศุภกฤต,1,Detached House,บ้าน,89.8,213.0,5630000.0,...,1.0,1.0,NaN,NaN,1.0,NaN,2021-11-12 13:17:15,2018-03-13 16:31:48,baania,https://baania.com/th/project/ศุภาลัย-การ์เด้น...
42561,36742,unittype_24495,project_9696,Cayla,1,Detached House,บ้าน,NaN,383.0,15230000.0,...,1.0,1.0,1.0,1.0,1.0,NaN,2021-11-12 13:18:33,2020-05-26 17:40:28,baania,https://baania.com/th/project/คาซาลูนา-เมสโต-โ...
42619,11944,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,NaN,353.0,23590000.0,...,1.0,1.0,1.0,1.0,1.0,NaN,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...

In [12]:
unit.iloc[0,:]

row_number                                                          27501
unittype_id                                                 unittype_9565
project_id                                                   project_2446
name_th                                                         2 Bedroom
propertytype_id                                                         2
propertytype_name_en                                                Condo
propertytype_name_th                                                คอนโด
area_total_min_wa                                                     NaN
area_usable_min                                                      37.3
price_min                                                       2500000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  NaN
count_parking                                                         NaN
count_room_bath                                                       1.0
count_room_bed                                                        2.0
count_room_dinning                                                    1.0
count_room_guest                                                      1.0
count_room_kitchen                                                    1.0
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2021-11-19 18:00:09
date_updated                                          2021-11-19 17:44:45
source                                                             baania
url_unittype            https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
Name: 0, dtype: object

In [13]:
unit.dropna(axis=1,thresh=42000) # axis 0 ลบยาว 1 ลบตั้ง thresh ลบกี่ค่า

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
...,...,...,...,...,...,...,...,...,...,...,...
42620,37109,unittype_38508,project_16864,Canola,1,Detached House,บ้าน,2021-11-12 13:22:37,2020-10-14 10:05:42,baania,https://baania.com/th/project/อิคอนเนเจอร์-พระ...
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42622,41009,617bde1687dd2300149d2195,617bdd47f62011001350de07,Grande,3,Townhome,ทาวน์โฮม,2021-11-12 13:34:17,2021-10-29 18:43:09,baania,https://baania.com/th/project/เดอะริคโค้-ทาวน์...
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [14]:
unit.head().dropna(thresh=10)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,NaN,28.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...

In [15]:
unit.head().dropna(axis=1,thresh=3)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_usable_min,price_min,count_room_bath,count_room_bed,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,37.3,2500000.0,1.0,2.0,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,150.0,2390000.0,3.0,3.0,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,28.0,NaN,1.0,1.0,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,27.0,170000.0,1.0,0.0,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,182.0,2390000.0,3.0,3.0,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...

In [16]:
unit.dropna(subset=['propertytype_name_en','price_min','area_usable_min']) # ทั้ง 3 column ไม่มี missing แน่นอน

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42618,22299,unittype_13674,project_5356,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,130.0,36500000.0,...,NaN,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:38:03,2020-10-14 00:47:50,baania,https://baania.com/th/project/บ้านศุธาวัลย์-53...
42619,11944,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,NaN,353.0,23590000.0,...,1.0,1.0,1.0,1.0,1.0,NaN,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,NaN,223.0,7490000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,...,NaN,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,NaN,170.0,3790000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [17]:
unit1 = unit.dropna(subset=['propertytype_name_en','price_min','area_usable_min']) # เอาตัวแปรมารับเพื่อนำตารางไปใช้ต่อ

In [18]:
unit1.shape

(31772, 27)

In [19]:
unit.shape

(42625, 27)

In [20]:
unit.dropna(subset=['propertytype_name_en','price_min','area_usable_min'],inplace=True) #inplac ไม่ต้องเอาอะไรมารับ จะทับตารางเดิม

In [21]:
unit.shape

(31772, 27)

## แทนค่า missing ด้วยค่าที่เราต้องการ (fillna())

In [22]:
unit.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...

In [23]:
unit.fillna(0)

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,0.0,37.3,2500000.0,...,1.0,1.0,0.0,0.0,0.0,0.0,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,0.0,27.0,170000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,0.0,182.0,2390000.0,...,1.0,1.0,0.0,0.0,2.0,0.0,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42618,22299,unittype_13674,project_5356,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,0.0,130.0,36500000.0,...,0.0,0.0,1.0,0.0,0.0,0.0,2020-12-04 10:38:03,2020-10-14 00:47:50,baania,https://baania.com/th/project/บ้านศุธาวัลย์-53...
42619,11944,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,0.0,353.0,23590000.0,...,1.0,1.0,1.0,1.0,1.0,0.0,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,0.0,223.0,7490000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,0.0,180.0,3200000.0,...,0.0,1.0,0.0,0.0,0.0,0.0,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,0.0,170.0,3790000.0,...,1.0,1.0,0.0,0.0,0.0,0.0,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [24]:
unit.fillna(value={'count_room_utility':0,'area_total_min_wa':unit['area_total_min_wa'].mean()})

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,44.084933,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,0.0,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.000000,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,0.0,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,44.084933,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,0.0,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,44.084933,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,0.0,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.500000,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,0.0,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42618,22299,unittype_13674,project_5356,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,44.084933,130.0,36500000.0,...,NaN,NaN,1.0,NaN,NaN,0.0,2020-12-04 10:38:03,2020-10-14 00:47:50,baania,https://baania.com/th/project/บ้านศุธาวัลย์-53...
42619,11944,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,44.084933,353.0,23590000.0,...,1.0,1.0,1.0,1.0,1.0,0.0,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,44.084933,223.0,7490000.0,...,NaN,NaN,NaN,NaN,NaN,0.0,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,44.084933,180.0,3200000.0,...,NaN,1.0,NaN,NaN,NaN,0.0,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,44.084933,170.0,3790000.0,...,1.0,1.0,NaN,NaN,NaN,0.0,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...

In [25]:
{'count_room_utility':0,'area_total_min_wa':unit['area_total_min_wa'].mean()}

{'count_room_utility': 0, 'area_total_min_wa': 44.084933035714286}

## วนลูป record ในตาราง (iterrows)

In [26]:
unit.iterrows()

In [27]:
for row in unit.head().iterrows():
    print(row)

(0, row_number                                                          27501
unittype_id                                                 unittype_9565
project_id                                                   project_2446
name_th                                                         2 Bedroom
propertytype_id                                                         2
propertytype_name_en                                                Condo
propertytype_name_th                                                คอนโด
area_total_min_wa                                                     NaN
area_usable_min                                                      37.3
price_min                                                       2500000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  NaN
count_parking                                                         NaN
count_room_bath                                                       1.0
count_room_bed                                                        2.0
count_room_dinning                                                    1.0
count_room_guest                                                      1.0
count_room_kitchen                                                    1.0
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2021-11-19 18:00:09
date_updated                                          2021-11-19 17:44:45
source                                                             baania
url_unittype            https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
Name: 0, dtype: object)
(1, row_number                                                          28777
unittype_id                                                unittype_10267
project_id                                                   project_3543
name_th                                                บ้านแฝดสองชั้น Z-2
propertytype_id                                                     20000
propertytype_name_en                                           Twin house
propertytype_name_th                                              บ้านแฝด
area_total_min_wa                                                    40.0
area_usable_min                                                     150.0
price_min                                                       2390000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  2.0
count_parking                                                         2.0
count_room_bath                                                       3.0
count_room_bed                                                        3.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2022-01-27 14:30:04
date_updated                                          2022-01-27 14:22:55
source                                                             baania
url_unittype            https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
Name: 1, dtype: object)
(3, row_number                                                          24988
unittype_id                                                unittype_19506
project_id                                                   project_7766
name_th                                                  Studio Floor 1-2
propertytype_id                                                         2
propertytype_name_en                                                Condo
propertytype_name_th                                                คอนโด
area_total_min_wa                                                     NaN
area_usable_min                                                      27.0
price_min                                                        170000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  NaN
count_parking                                                         NaN
count_room_bath                                                       1.0
count_room_bed                                                        0.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2020-12-04 10:40:59
date_updated                                          2020-10-14 01:06:48
source                                                             baania
url_unittype            https://baania.com/th/project/บ้านสวนชมน้ำ-776...
Name: 3, dtype: object)
(4, row_number                                                          38596
unittype_id                                                unittype_10290
project_id                                                   project_3551
name_th                                                              TH 3
propertytype_id                                                         3
propertytype_name_en                                             Townhome
propertytype_name_th                                             ทาวน์โฮม
area_total_min_wa                                                     NaN
area_usable_min                                                     182.0
price_min                                                       2390000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  3.0
count_parking                                                         2.0
count_room_bath                                                       3.0
count_room_bed                                                        3.0
count_room_dinning                                                    1.0
count_room_guest                                                      1.0
count_room_kitchen                                                    1.0
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    2.0
count_room_utility                                                    NaN
date_created                                          2021-11-12 13:30:08
date_updated                                          2021-02-03 12:12:54
source                                                             baania
url_unittype            https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
Name: 4, dtype: object)
(5, row_number                                                          30766
unittype_id                                                 unittype_8026
project_id                                                   project_2694
name_th                                                     Luciano Grand
propertytype_id                                                         1
propertytype_name_en                                       Detached House
propertytype_name_th                                                 บ้าน
area_total_min_wa                                                    70.5
area_usable_min                                                     198.0
price_min                                                      11700000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  2.0
count_parking                                                         2.0
count_room_bath                                                       4.0
count_room_bed                                                        3.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2021-11-12 13:22:43
date_updated                                          2020-10-14 19:35:20
source                                                             baania
url_unittype            https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...
Name: 5, dtype: object)

In [28]:
for row in unit.head(20).iterrows():
    if 'project_' not in row[1] ['project_id']: 
       print(row)

(8, row_number                                                          41823
unittype_id                                      6215b4a7a441d30014e1f02f
project_id                                       6215b1cfc1620300140bc087
name_th                                        บ้านเดี่ยวชั้นเดียว Type C
propertytype_id                                                         1
propertytype_name_en                                       Detached House
propertytype_name_th                                                 บ้าน
area_total_min_wa                                                     NaN
area_usable_min                                                      80.0
price_min                                                        990000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  1.0
count_parking                                                         1.0
count_room_bath                                                       1.0
count_room_bed                                                        2.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2022-02-23 12:00:12
date_updated                                          2022-02-23 11:14:31
source                                                             baania
url_unittype            https://baania.com/th/project/เฌอลินน์ดา-ซำสูง...
Name: 8, dtype: object)
(16, row_number                                                          41850
unittype_id                                      621700a8a441d30014e1f0f3
project_id                                       6216fee6a441d30014e1f0f2
name_th                                               บ้านเดี่ยวชั้นเดียว
propertytype_id                                                         1
propertytype_name_en                                       Detached House
propertytype_name_th                                                 บ้าน
area_total_min_wa                                                     NaN
area_usable_min                                                      83.0
price_min                                                       2200000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  1.0
count_parking                                                         2.0
count_room_bath                                                       2.0
count_room_bed                                                        3.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2022-02-24 12:00:06
date_updated                                          2022-02-24 11:38:52
source                                                             baania
url_unittype            https://baania.com/th/project/อินทรวิลเลจ-6216...
Name: 16, dtype: object)
(23, row_number                                                          19479
unittype_id                                      60113e51061df200134fb4ef
project_id                                       5e8bfc839f161600121b497d
name_th                                                 บ้านเดี่ยวสองชั้น
propertytype_id                                                         1
propertytype_name_en                                       Detached House
propertytype_name_th                                                 บ้าน
area_total_min_wa                                                     NaN
area_usable_min                                                     300.0
price_min                                                       9900000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  2.0
count_parking                                                         2.0
count_room_bath                                                       4.0
count_room_bed                                                        4.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     2.0
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2021-11-12 13:29:44
date_updated                                          2021-01-27 17:22:06
source                                                             baania
url_unittype            https://baania.com/th/project/ไพรเวท-33-5e8bfc...
Name: 23, dtype: object)
(24, row_number                                                          17281
unittype_id                                      5f27d69182035a001a6f333e
project_id                                       5f0d4f38b285eb00194decde
name_th                                                            Studio
propertytype_id                                                         2
propertytype_name_en                                                Condo
propertytype_name_th                                                คอนโด
area_total_min_wa                                                     NaN
area_usable_min                                                      26.0
price_min                                                       1790000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  NaN
count_parking                                                         NaN
count_room_bath                                                       1.0
count_room_bed                                                        0.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2022-04-26 15:30:06
date_updated                                          2022-04-26 15:19:49
source                                                             baania
url_unittype            https://baania.com/th/project/ดีคอนโด-ไฮด์อเวย...
Name: 24, dtype: object)
(25, row_number                                                          17337
unittype_id                                      5f2d048d306e7e0019068fad
project_id                                       5f2cdf27306e7e0019068f25
name_th                                                  โฮมออฟฟิศสามชั้น
propertytype_id                                                         6
propertytype_name_en                                          Home office
propertytype_name_th                                            โฮมออฟฟิศ
area_total_min_wa                                                     NaN
area_usable_min                                                     210.0
price_min                                                       6300000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  3.0
count_parking                                                         1.0
count_room_bath                                                       4.0
count_room_bed                                                        3.0
count_room_dinning                                                    1.0
count_room_guest                                                      1.0
count_room_kitchen                                                    NaN
count_room_living                                                     1.0
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2021-11-12 13:18:59
date_updated                                          2020-08-07 14:38:19
source                                                             baania
url_unittype            https://baania.com/th/project/นิวเอจ-สตูดิโอเฮ...
Name: 25, dtype: object)

*ans* มี 5 อัน

In [29]:
for row in unit.iterrows():
    if 'สตูดิโอ' not in row[1] ['url_unittype']:
       print(row[1] ['url_unittype'])

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
https://baania.com/th/project/บ้านพิมานธานีโนนทัน-6-1988/อาคารพาณิชย์-unittype_5996
https://baania.com/th/project/เซ็นทริค-สถานี-ติวานนท์-7652/2-bedroom-tower-a-floor-37-40-unittype_19736
https://baania.com/th/project/รุ่งเรือง-ควอลิตี้เฮ้าส์-2-1207/รุ่งอรุณ-unittype_3860
https://baania.com/th/project/ฟลอรัลเชียงใหม่คอนโดมิเนียม-707/คอนโดมิเนียม-unittype_1455
https://baania.com/th/project/เรซิโอ-โฮม-วงแหวน-รามอินทรา-16834/rest-unittype_38367
https://baania.com/th/project/พฤกษา-วิลเลจ-5-วงแหวน-รัตนาธิเบศร์-12685/บ้านเดี่ยวสองชั้น-unittype_30141
https://baania.com/th/project/ชวนชื่น-ไพร์ม-วิลเลจ-บางนา-5e81a847b422610019688550/botanic-5e81a953b422610019688554
https://baania.com/th/project/มารุ-เอกมัย-2-13041/2-bedroom-unittype_30969
https://baania.com/th/project/แอสปาย-รัตนาธิเบศร์-4003/2-bedroom-floor-17-20-unittype_15264
https://baania.com/th/project/เดอะ-เกรท-อัพ-ทาวน์-9143/อาคารพาณิชย์สี่ชั้น-unittype_22613
https://baania.com/th/project/ซื่อตรง-พรีเมี่ยม-พระราม-2-แสมดำ-5138/gold-d-unittype_13267
https://baania.com/th/project/เพฟ-ปิ่นเกล้า-ศาลายา-16895/coton-unittype_38610
https://baania.com/th/project/เซียล่า-ศรีปทุม-17436/1-bedroom-suite-unittype_39966
https://baania.com/th/project/เดอะ-ไพรเวซี่-เรวดี-2071/1-bedroom-type-a-tower-c-floor-3-4-unittype_14928
https://baania.com/th/project/บ้านสายชล-13626/ทาวน์โฮมสองชั้น-unittype_32150
https://baania.com/th/project/บ้านธัญญธานี-จอหอ-1701/บ้านเดี่ยวสองชั้น-type-b-unittype_5183
https://baania.com/th/project/รอยัล-วิว-วิลเลจ-11003/บ้านเดี่ยวชั้นเดียว-unittype_27158
https://baania.com/th/project/บ้านรุ่งธนา-3-774/บ้านธนภรณ์3-บ้านชั้นเดียว-unittype_3144
https://baania.com/th/project/อินทราคอนโดวิลล์-4425/studio-unittype_11996
https://baania.com/th/project/เอกสินคอนโดมิเนียม-7624/studio-floor-3-4-unittype_19784
https://baania.com/th/project/บ้านปิยวรารมย์-3-4904/ทาวน์โฮมสองชั้น-unittype_12817
https://baania.com/th/project/บ้านรัตนโกสินทร์-200-ปี-5789/บ้านเดี่ยวชั้นเดียว-type-a-unittype_14492
https://baania.com/th/project/ขวัญนคร-ดีไลท์-5f351121c801fb0019dacdbb/บ้านเดี่ยวชั้นเดียว-5f35119ec801fb0019dacdc5
https://baania.com/th/project/ทู-แกรนด์-โมนาโค-บางนา-วงแหวน-12711/ปาลา-เดอ-แปงซ์-unittype_30184
https://baania.com/th/project/บ้านบริบูรณ์-มาบข่า-11802/บ้านเดี่ยวชั้นเดียว-type-c-unittype_28887
https://baania.com/th/project/เดอะ-ไลน์-สุขุมวิท-101-2677/2-bedrooms-duplex-unittype_7948
https://baania.com/th/project/เซ็นทริค-สถานี-ติวานนท์-7652/1-bedroom-tower-a-floor-37-40-unittype_19709
https://baania.com/th/project/บางกอก-การ์เด้น-9231/1-bedroom-unittype_23133
https://baania.com/th/project/สกาย-วอล์ค-คอนโดมิเนียม-12272/studio-unittype_29550
https://baania.com/th/project/เดอะริช-ทาวน์-3-15426/บ้านแฝดสองชั้น-unittype_36003
https://baania.com/th/project/ร่มเย็นคอนโดมิเนียม-4739/studio-floor-3-4-unittype_18610
https://baania.com/th/project/มาลาดา-โฮม-แอนด์-รีสอร์ท-เชียงใหม่-84/single-villa-ขายแล้ว-unittype_263
https://baania.com/th/project/พาทาโกเนีย-รามอินทรา-นิมิตรใหม่-4788/อาคารพาณิชย์สี่ชั้น-unittype_12617
https://baania.com/th/project/เดอะ-เรสซิเดนซ์-แอท-แมนดาริน-โอเรียนเต็ล-8079/2-bedroom-c-unittype_20648
https://baania.com/th/project/เมซองเดอวิลล์-4403/1-bedroom-unittype_11968
https://baania.com/th/project/บ้านราชาวดี-พุทธบูชา-36-16656/บ้านเดี่ยวสองชั้น-unittype_37786
https://baania.com/th/project/ศุภาลัย-ซิตี้-รีสอร์ท-รัชโยธิน-พหลโยธิน-32-6636/superior-suite-unittype_17055
https://baania.com/th/project/สิริศา-14-10281/บ้านเดี่ยวชั้นเดียว-unittype_25704
https://baania.com/th/project/บ้านบุรีรมย์-12609/บ้านเดี่ยวสองชั้น-unittype_30025
https://baania.com/th/project/เรสท์-บางใหญ่-5e60d3f35396bf0012e94217/woodic-5e60d5995396bf0012e94222
https://baania.com/th/project/ว-แลนด์เฮ้าส์-ทวีไทย-3-13779/เรือนดาวคู่-unittype_32463
https://baania.com/th/project/เศรษฐสิริ-พหล-วัชรพล-15373/peerless-5f58a963cb4b26001980b747
https://baania.com/th/project/จันทิมา-ซิตี้-12750/บ้านแฝดสองชั้น-unittype_30246
https://baania.com/th/project/เศรษฐสิริ-แจ้งวัฒนะ-ประชาชื่น-2086/ingenia-f-ขายแล้ว-unittype_6548
https://baania.com/th/project/ฉัตรเพชร-พาร์ค-คอนโด-5ea27d8078b3120012dd4c70/2-bedroom-5ea27f8178b3120012dd4c75
https://baania.com/th/project/ดีคอน-ไพร์ม-รัตนาธิเบศร์-2046/2-bedroom-type-c-unittype_6176
https://baania.com/th/project/เดอะ-กรีน-เกรซ-บางแสน-คอนโดมิเนียม-10816/1-bedroom-unittype_26816
https://baania.com/th/project/อรสิริน-บิสซิเนส-เซ็นเตอร์-5-สันทราย-1199/อาคารพาณิชย์สามชั้น-unittype_3736
https://baania.com/th/project/เพลินฝัน-พาร์ควิลล์-11583/บ้านเดี่ยวชั้นเดียว-unittype_28342
https://baania.com/th/project/เกษมสุข-11987/บ้านเดี่ยวสองชั้น-unittype_29126
https://baania.com/th/project/การ์เด้นสแควร์-13113/อาคารพาณิชย์สามชั้น-unittype_31144
https://baania.com/th/project/เดอะลิฟวิ่ง-2-บ้านกล้วย-ไทรน้อย-5ece2dd0292ffd0019214d70/บ้านเดี่ยวสองชั้น-5ece2e7c292ffd0019214d7c
https://baania.com/th/project/กัสโต้-ทาวน์โฮม-ท่าน้ำนนท์-พระราม-5-2063/type-b-unittype_6551
https://baania.com/th/project/เดอะ-มาสเตอร์พีช-ซีนเนอรี่-ฮิลล์-34/supamongkol-unittype_67
https://baania.com/th/project/วี-พร็อพเพอร์ตี้-ร-8-มข-1869/ixora-unittype_5739
https://baania.com/th/project/แกรนด์-ธัญญวันท์-โฮม-2-3-10820/บ้านเดี่ยวชั้นเดียว-unittype_26823
https://baania.com/th/project/เดอะ-คริส-คอนโดเทล-ป่าตอง-13504/2-bedroom-unittype_31925
https://baania.com/th/project/เพชรวิลล่า-2-13651/ทาวน์โฮมสองชั้น-unittype_32209
https://baania.com/th/project/ไทยมณี-คอนโดมิเนียม-6186/studio-unittype_15851
https://baania.com/th/project/เดอะ-สปริง-คอนโด-152/type-l-unittype_2248
https://baania.com/th/project/ลิขิตรา-แกรนด์การ์เด้นวิลล์-1928/แก้วกัลยา-unittype_5873
https://baania.com/th/project/เออร์เบิร์น-มิกซ์-หางดง-5670/อาคารพาณิชย์สามชั้นครึ่ง-unittype_14272
https://baania.com/th/project/ซิตี้-พาร์ค-คอนโด-บี-1865/type-a-unittype_5644
https://baania.com/th/project/เดอะ-พาโนล่า-พัทยา-5e940bad9f161600121b52db/1-bedroom-5e940c5f9f161600121b52df
https://baania.com/th/project/ศุภาลัย-พาร์ควิลล์-ช้างเผือก-101/ศุภพัฒน์-unittype_346
https://baania.com/th/project/โกลเด้น-ทาวน์-3-บางนา-สวนหลวง-16852/น็อตติ้ง-ฮิลล์-unittype_38410
https://baania.com/th/project/เดอะ-พาลาซโซ่-ปิ่นเกล้า-5f0e7ba6b285eb00194def62/antonio-5f0e7e2ab285eb00194def68
https://baania.com/th/project/เลอ-พรีเมีย-2-15271/duplexes-unittype_35608
https://baania.com/th/project/วันพลัส-นายน์ทีน-2-1087/1-bedroom-unittype_2775
https://baania.com/th/project/มาย-คอนโด-ลาดพร้าว-27-15791/studio-unittype_36991
https://baania.com/th/project/เดอะ-ซิตี้-รามอินทรา-2-5e8d92879f161600121b4e10/vireo-5e8d931d9f161600121b4e19
https://baania.com/th/project/สิริรดา-บ้านทิวเขา-สารภี-กู่แดง-15101/บ้านทิวเขา-4-unittype_35190
https://baania.com/th/project/เดอะ-โคลด์-เม้าน์เท่น-เรสซิเดนซ์-เขาใหญ่-1519/1-bedroom-type-a-unittype_4683
https://baania.com/th/project/พฤกษาวิลล์-73-พัฒนาการ-38-8895/บ้านแฝดสองชั้น-unittype_22087
https://baania.com/th/project/บดินทร-2-ซาฟารี-รามอินทรา-16405/ทาวน์โฮมสองชั้น-unittype_37572
https://baania.com/th/project/ลินดาเฮาส์-10699/ทาวน์โฮมสองชั้น-unittype_26587
https://baania.com/th/project/แอล-ลอฟท์-รัชดา-19-7728/1-bedroom-unittype_19456
https://baania.com/th/project/อาร์โค่-7511/type-b-unittype_35185
https://baania.com/th/project/เดอะ-ทรัสต์-คอนโด-หัวหิน-9199/2-bedroom-unittype_22752
https://baania.com/th/project/วีเอ็น-เรสซิเดนซ์-3-11191/1-bedroom-unittype_27560
https://baania.com/th/project/วันพลัส-สวนดอก-4-5-6-77/oneplus-6-type-h-unittype_5530
https://baania.com/th/project/ดีลักซ์-คอนโดมิเนียม-13269/1-bedroom-unittype_31457
https://baania.com/th/project/บ้านวราทรัพย์-10613/ทาวน์โฮมชั้นเดียว-unittype_26344
https://baania.com/th/project/ศุภาลัย-ไพรด์-บางนา-วงแหวน-3701/ศุภฤทัย-unittype_10957
https://baania.com/th/project/ไอลีฟ-ไพร์ม-พัทยา-จอมเทียน-620242c5591c4600138e6267/ทาวน์โฮมสองชั้น-type-b-620245091851bf001506472b
https://baania.com/th/project/88-แลนด์-แอนด์-เฮ้าส์-เกาะแก้ว-13202/massivo-unittype_31350
https://baania.com/th/project/ดิอามองต์-คอนโดมิเนียม-81/1-bedroom-unittype_2584
https://baania.com/th/project/พรีเมี่ยม-ไทม์โฮม-สวนหลวง-ร-9-8826/kare-unittype_21990
https://baania.com/th/project/สิริวลัย-รังสิต-คลอง-1-3445/บ้านสิริอาภา-e4-unittype_10026
https://baania.com/th/project/บริทาเนีย-ศรีนครินทร์-14987/brompton-unittype_34840
https://baania.com/th/project/ซิตี้ลิงค์-คอนโด-ซิดนีย์-1812/studio-unittype_5411
https://baania.com/th/project/ศุภาลัย-พาร์ควิลล์-รามอินทรา-23-6603/ศุภอาภา-unittype_16665
https://baania.com/th/project/แลนด์มาร์ค-แอท-แกรนด์-สเตชั่น-605c40d22fcbdb0013a4ac2f/1-bedroom-605c42315776860014a1f8fa
https://baania.com/th/project/เดอะวิน-แดงใหญ่-6217de5dc1620300140bc1b2/บ้านเดี่ยวชั้นเดียว-6217deb1c1620300140bc1b5
https://baania.com/th/project/มลิวัลย์วิลล่า-4-14482/บ้านเดี่ยวชั้นเดียว-unittype_33797
https://baania.com/th/project/ลลิล-ทาวน์-แลนซีโอ-คริป-บางนา-เทพารักษ์-5e8d7f129f161600121b4d81/renoir-5e8d88679f161600121b4de0
https://baania.com/th/project/สราญสิริ-ประชาอุทิศ-สุขสวัสดิ์-3107/สราญรมัย-unittype_9078
https://baania.com/th/project/เนอวาน่า-แอท-เวิร์ค-พระราม-9-รามคำแหง-8900/complete-unittype_22097
https://baania.com/th/project/โกลเด้น-ทาวน์-ลาดพร้าว-เกษตรนวมินทร์-2827/เค็นชิงตัน-unittype_8357
https://baania.com/th/project/เดอะ-ลีเจ้นท์-ศาลาแดง-6794/1-bedroom-unittype_17072
https://baania.com/th/project/พฤกษาวิลล์-50-2-รามคำแหง-ซอยมีสทิน-17339/spring-unittype_39731
https://baania.com/th/project/อาคารพาณิชย์-คาซ่า-นาวี-11454/อาคารพาณิชย์สามชั้น-unittype_28017
https://baania.com/th/project/บ้านฟ้าปิยรมย์-นีวา-3549/เรน่า-unittype_34934
https://baania.com/th/project/ไอวี่-ทาวน์-2-11116/ทาวน์โฮมสองชั้น-unittype_27386
https://baania.com/th/project/คอลเลจวิว-คอนโด-11415/2-bedroom-unittype_27944
https://baania.com/th/project/ลุมพินี-เพลส-วอเตอร์คลิฟ-6713/studio-unittype_18020
https://baania.com/th/project/บุราสิริ-รังสิต-3655/cinnamon-unittype_10540
https://baania.com/th/project/บุราสิริ-รังสิต-3655/cumin-unittype_10539
https://baania.com/th/project/แอสปาย-พระราม9-7865/1-bedroom-unittype_20011
https://baania.com/th/project/ทาวน์โฮมบ้านฉาง-12970/ทาวน์โฮมสองชั้น-ขายแล้ว-unittype_30644
https://baania.com/th/project/แกรนด์-พาราโน่-202/type-a-unittype_634
https://baania.com/th/project/โกลเด้น-คอนโด-เครือสหพัฒน์-5f057c4bb285eb00194de4f4/studio-5f057ceeb285eb00194de500
https://baania.com/th/project/ภูวารี-วิลล่า-1374/ภูชลธาร-unittype_4186
https://baania.com/th/project/เซ็นทริค-สถานี-ติวานนท์-7652/2-bedroom-tower-b-floor-17-20-unittype_19744
https://baania.com/th/project/สาทร-พระลือ-สิงหวัฒน์-15202/อาคารพาณิชย์สามชั้น-unittype_35430
https://baania.com/th/project/เดอะ-เลคส์-คอนโดมิเนียม-3860/2-bedroom-unittype_11082
https://baania.com/th/project/ริเวนเดลล์-เอสเตรญ่า-16265/1-bedroom-unittype_37350
https://baania.com/th/project/ว-แลนด์เฮ้าส์-โคกสูง-17402/เรือนลีลาวดี-unittype_39876
https://baania.com/th/project/เดอะ-นิช-ไอดี-เสรีไทย-เฟส1-2975/type-c-unittype_20190
https://baania.com/th/project/ศุภาลัย-เบลล่า-แม่กรณ์-เชียงราย-17531/ศุภสิทธิ์-unittype_40216
https://baania.com/th/project/บ้านกลางเมือง-4-นาดี-14903/บ้านเดี่ยวชั้นเดียว-unittype_34588
https://baania.com/th/project/พลีโน่-รามอินทรา-จตุโชติ-5fab9af92aaf680012207b3c/ทาวน์โฮมสองชั้น-5fab9b94ee0d7f0012409c63
https://baania.com/th/project/แชปเตอร์-จุฬา-สามย่าน-17141/1-bedroom-unittype_39252
https://baania.com/th/project/พาร์ค-เอเวนิว-ไพรเวท-15371/laurel-unittype_35871
https://baania.com/th/project/เชียงใหม่ล้านนา-วิลเลจ-เฟส-2-1012/บ้าน-125-ตารางเมตร-unittype_1947
https://baania.com/th/project/บ้านสวนกลางดง-17423/plan-c-unittype_39931
https://baania.com/th/project/ริธึ่ม-เจริญกรุง-พาวิลเลี่ยน-5e5e09fc35e8160012b45559/1-bedroom-5e5e0ac735e8160012b4555b
https://baania.com/th/project/สิริ-เพลส-บางใหญ่-17159/loft-93-unittype_39305
https://baania.com/th/project/พฤกษาวิลล์-57-พัฒนาการ-8020/บ้านแฝดสองชั้น-ขายแล้ว-unittype_20468
https://baania.com/th/project/ศุภาลัย-พรีโม่-บางแสน-9537/ศุภดำรง-ใหม่-unittype_23891
https://baania.com/th/project/สิริมงคล-9-สแกนดิเนเวีย-5ffc1015c48e6b001289e43b/bergen-5ffc129885111e0012890b25
https://baania.com/th/project/เดอะ-วิช-คอนโด-5ecb8b7459e5460012c7b97b/1-bedroom-5ecb8d2c59e5460012c7b987
https://baania.com/th/project/น็อตติ้ง-ฮิลล์-ติวานนท์-แคราย-2087/1-bedroom-plus-type-suite-unittype_9804
https://baania.com/th/project/บ้านพงษ์พจน์-วิลล่า-7176/ทาวน์โฮมสองชั้น-unittype_17901
https://baania.com/th/project/เดอะโคสต์-แบงค็อก-2695/2-bedroom-duplex-unittype_8014
https://baania.com/th/project/คาซ่า-แกรนด์-ศรีราชา-9203/single-house-claudia-ขายแล้ว-unittype_22760
https://baania.com/th/project/เดอะ-พรีเมียม-วิลล์-อุดรธานี-5ea6aa9278b3120012dd5096/บ้านเดี่ยวชั้นเดียว-5ea6ab0478b3120012dd509a
https://baania.com/th/project/กิตตินคร-กรีนวิลล์-9073/บ้านแฝดสองชั้น-type-a-unittype_22489
https://baania.com/th/project/สิวารมณ์-ปาร์ค-สุขุมวิท-บางปู-17336/brighton-unittype_39725
https://baania.com/th/project/ศุภาลัย-พาร์ควิลล์-รังสิต-คลอง-4-5ec3952084c1860019f32c06/ศุภราช-5ec3959084c1860019f32c23
https://baania.com/th/project/เดอะ-ทรี-หัวหมาก-อินเตอร์เชนจ์-17285/1-bedroom-unittype_39586
https://baania.com/th/project/อาคารพาณิชย์มิสเตอร์เอ-มาบตาพุด-12965/อาคารพาณิชย์สามชั้น-unittype_30639
https://baania.com/th/project/เดอะ-เดคโค่-หนองละลอก-บ้านค่าย-ระยอง-15442/บ้านแฝดชั้นเดียว-unittype_36039
https://baania.com/th/project/เดอะ-วิลเลจ-บางนา-วงแหวน-3-15344/บ้านเดี่ยวสองชั้น-unittype_35791
https://baania.com/th/project/เดอะ-ไพรเวซี่-ท่าพระ-อินเตอร์เชนจ์-14654/combined-unittype_34117
https://baania.com/th/project/เซนโทร-รามอินทรา-จตุโชติ-15515/new-series-sunshine-unittype_36205
https://baania.com/th/project/บ้านเชียงใหม่พฤกษาโฮม-86/บ้านไพรพฤกษ์-ขายแล้ว-unittype_9856
https://baania.com/th/project/เดอะ-ไลน์-สุขุมวิท-71-7926/1-bedroom-unittype_20185
https://baania.com/th/project/เดอะ-ริทซ์-คาร์ลตัน-เรสซิเดนเซส-บางกอก-7965/2-bedroom-duplex-unittype_20294
https://baania.com/th/project/บ้านรชยา-บ้านช้าง-2-14508/บ้านแฝดสองชั้น-unittype_33871
https://baania.com/th/project/ธัญดา-พาร์ควิว-2-แพรกษา-เทพารักษ์-17213/ทาวน์โฮมสองชั้น-type-a-unittype_39438
https://baania.com/th/project/มายฮิป-คอนโด-2-3-4-108/2-bedroom-my-hip-condo-3-unittype_2121
https://baania.com/th/project/บ้านสกุลธร-12189/บ้านเดี่ยวสองชั้น-unittype_29416
https://baania.com/th/project/เอส-ฟิฟตี้-คลาวด์-พัทยา-9772/studio-unittype_24463
https://baania.com/th/project/พรทวีวัฒน์-คอนโดมิเนียม-6045/studio-unittype_15401
https://baania.com/th/project/เวิร์ค-แอด-ไลฟ์-นวมินทร์-36-15574/โฮมออฟฟิศสี่ชั้น-unittype_36344
https://baania.com/th/project/ฉัตรเพชร-เอ็กซ์-การ์เด้นวิลล์-5ea1659038be3400128e3689/สุวดี-5ea169b038be3400128e36a2
https://baania.com/th/project/บ้านลลิล-อินเดอะ-พาร์ค-พระราม-2-เอกชัย-3513/ลลิลธาร-unittype_10218
https://baania.com/th/project/พาราไดซ์-เพลส-คอนโด-10721/standard-unittype_26687
https://baania.com/th/project/วิชั่นวิลล์-3-4015/ทาวน์โฮมสามชั้น-unittype_11363
https://baania.com/th/project/คีรีมายา-เรสซิเดนส์-อัตตา-เดอะคอนโด-1493/2-bedroom-unittype_4556
https://baania.com/th/project/เดอะ-ลิฟวิ่ง-3-บาย-คุณาลัย-2258/b-series-unittype_6798
https://baania.com/th/project/คอนโด-เลต-มิสท์-พระราม-9-2455/3-bedroom-unittype_7393
https://baania.com/th/project/ธารา-ราชพฤกษ์-ปิ่นเกล้า-2294/tawin-b-unittype_6889
https://baania.com/th/project/อควา-ดิวิน่า-รามคำแหง-94-2721/bella-bulla-unittype_8090
https://baania.com/th/project/เย็นสบายดี-ลาดพร้าว-122-5e687218c91cd3001289506f/type-e-5e687e74c91cd30012895087
https://baania.com/th/project/ซี-เพลส-ลาดพร้าว-18-5ecf6f0001762c0019ce5963/1-bedroom-5ecf6f8701762c0019ce5968
https://baania.com/th/project/บ้านศิรินเทพ-ลาดพร้าว-101-12390/บ้านแฝดสองชั้น-unittype_29713
https://baania.com/th/project/จิรันตน์-9164/ทาวน์โฮมสองชั้น-unittype_22669
https://baania.com/th/project/ปาล์มสปริงส์-12-13672/ศุภสิทธิ์-unittype_32244
https://baania.com/th/project/ฟิวส์-จันทน์-สาทร-3096/2-bedrooms-unittype_9038
https://baania.com/th/project/วิสซ์ดอม-อเวนิว-รัชดา-ลาดพร้าว-8332/studio-unittype_21260
https://baania.com/th/project/เดอะ-ทรอป-อ่อนนุช-สุวรรณภูมิ-6686/ทาวน์โฮมสองชั้น-type-a-unittype_16844
https://baania.com/th/project/พิมานดา-เซน-12551/บ้านเดี่ยวสองชั้น-unittype_29929
https://baania.com/th/project/มณฑนา-คอนโดมิเนียม-10711/studio-unittype_26613
https://baania.com/th/project/อัญรัตน์เพลส-10906/1-bedroom-unittype_27025
https://baania.com/th/project/ศรีสุชาติ-3-13361/บ้านแฝดชั้นเดียว-unittype_31648
https://baania.com/th/project/ลา-ซิตต้า-เดลเร-ทองหล่อ-16-5e68aa37c91cd30012895100/3-bedroom-5e68be4ac91cd3001289512a
https://baania.com/th/project/เพอร์เฟค-เพลส-พัฒนาการ-ศรีนครินทร์-2557/victor-unittype_7615
https://baania.com/th/project/ชัยพฤกษ์-เพชรเกษม-81-6319/พฤกษ์วารี-ap-unittype_16116
https://baania.com/th/project/บ้านกลางเมือง-5-14514/บ้านเดี่ยวชั้นเดียว-unittype_33880
https://baania.com/th/project/แพรมาพร-ลำลูกกาคลอง-7-12778/ทาวน์โฮมสองชั้น-unittype_30292
https://baania.com/th/project/แกรนด์-ซีทรู-624fbc13c396090014aef4e4/บ้านเดี่ยวสองชั้น-624fc0ccc496d70014da915f
https://baania.com/th/project/วิเศษสิริ-2-8398/บ้านเดี่ยวชั้นเดียว-type-b-unittype_21423
https://baania.com/th/project/โอเรียลเต็ล-ทาวเวอร์-16455/4-bedroom-unittype_37694
https://baania.com/th/project/เดอะ-เบสท์-บาย-สิรารมย์-โคกกรวด-ยางน้อย-1569/สิวาลัย-unittype_4921
https://baania.com/th/project/เอ็ม-ที-คอนโดมิเนียม-บางบัวทอง-7769/studio-floor-3-4-unittype_19530
https://baania.com/th/project/เกตเวย์-เฮ้าส์-ฉะเชิงเทรา-5e84193ae146a400123ef052/newport-5e841c3ee146a400123ef05e
https://baania.com/th/project/ทรี-คอนโด-สุขุมวิท-42-6705/1-bedroom-unittype_16901
https://baania.com/th/project/บ้านปัญฐิญา-แพรกษา-7250/บ้านแฝดสองชั้น-สไตล์โมเดิร์น-unittype_18039
https://baania.com/th/project/วัน-อัลติจูด-เจริญกรุง-5e7b320d0b71920019aa9337/4-bedroom-5eba7b4b42ad800019cd14eb
https://baania.com/th/project/เดอะ-ซีน-บางแสน-9796/studio-unittype_24553
https://baania.com/th/project/ไอลีฟ-ทาวน์-เศรษฐกิจ-บางปลา-5f3e31866320a60019751189/orchid-5f3e32296320a600197511a0
https://baania.com/th/project/งามวดีเพลส-4561/1-bedroom-unittype_12199
https://baania.com/th/project/บาโรเนียทาวน์-ท่าน้ำนนท์-4327/ทาวน์โฮมสามชั้น-unittype_11854
https://baania.com/th/project/พลัมคอนโด-ปิ่นเกล้า-สเตชั่น-2797/1-bedroom-unittype_8266
https://baania.com/th/project/บ้านวรัญญู-1-6588/บ้านเดี่ยวสองชั้น-unittype_16639
https://baania.com/th/project/บ้านสวนศิรดา-13771/บ้านเดี่ยวสองชั้น-unittype_32445
https://baania.com/th/project/ศุภาลัย-โนโววิลล์-แอร์พอร์ต-1872/ศุภชีวัน-unittype_5878
https://baania.com/th/project/อีลิท-ศาลายา-3478/2-bedroom-unittype_10093
https://baania.com/th/project/เซนโทร-รังสิต-3731/bravo-b-unittype_38976
https://baania.com/th/project/มัณฑนา-มอเตอร์เวย์-โคราช-61f3583757a0db00146b83e4/cozy-6229b3fc587c1b00149b6bce
https://baania.com/th/project/ซิตี้พาร์ค-บางใหญ่-12753/ทาวน์โฮมสองชั้น-unittype_30250
https://baania.com/th/project/เดอะ-ซิตี้-ราชพฤกษ์-จรัญฯ13-2775/finch-unittype_8207
https://baania.com/th/project/เดอะ-ไลท์-นิวยอร์ก-8016/1-bedroom-unittype_20450
https://baania.com/th/project/ดิ-เอสตีม-เชียงใหม่-1104/cozy-unittype_32136
https://baania.com/th/project/เอ็ม-จตุจักร-2551/1-bedroom-unittype_7591
https://baania.com/th/project/เดอะทรี-อินเตอร์เชนจ์-3263/2-bedrooms-unittype_9536
https://baania.com/th/project/เดอะ-กรีนเนอร์รี่-7-ปิ่นเกล้า-พุทธมณฑล-9015/ทาวน์โฮมสองชั้น-unittype_22385
https://baania.com/th/project/เดอะ-วอเตอร์ฟอร์ด-สุขุมวิท-50-3832/studio-unittype_19712
https://baania.com/th/project/ศรีราชา-เพลส-16269/1-bedroom-unittype_37458
https://baania.com/th/project/บ้านสิริเย็นอากาศ-9263/1-bedroom-unittype_23188
https://baania.com/th/project/บ้านรัตนบุรี-1325/ฮาบิแทต-h-150-unittype_4088
https://baania.com/th/project/ไอดีโอ-โมบิ-พระราม-9-2472/1-bedroom-unittype_7435
https://baania.com/th/project/ฐิติพร-พรีเมียร์-1372/premier-1-unittype_4312
https://baania.com/th/project/หัวหิน-ไนซ์-บรีซ-7-14392/l-shape-unittype_33633
https://baania.com/th/project/บ้านศิรินธรไพรเวทโฮม-7778/บ้านเดี่ยวสองชั้น-unittype_19570
https://baania.com/th/project/บางกอก-บูเลอวาร์ด-ราชพฤกษ์-พระราม-5-2-2069/silver-rhine-unittype_6222
https://baania.com/th/project/สุนิสา-เพลส-คอนโด-11163/studio-unittype_27489
https://baania.com/th/project/บ้านบุษบาวิลล์-5289/ทาวน์โฮมสองชั้น-unittype_13539
https://baania.com/th/project/วิลล่า-โนวา-เทพารักษ์-3678/mono-unittype_10708

In [30]:
for row in unit.head(2).iterrows(): #มีสมาชิก 2
     print(row) 
     print('จำนวนสมาชิก ',len(row))
     print('สมาชิกตัวที่ 1' ,row[0])
     print('สมาชิกตัวที่ 2' ,row[1])

(0, row_number                                                          27501
unittype_id                                                 unittype_9565
project_id                                                   project_2446
name_th                                                         2 Bedroom
propertytype_id                                                         2
propertytype_name_en                                                Condo
propertytype_name_th                                                คอนโด
area_total_min_wa                                                     NaN
area_usable_min                                                      37.3
price_min                                                       2500000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  NaN
count_parking                                                         NaN
count_room_bath                                                       1.0
count_room_bed                                                        2.0
count_room_dinning                                                    1.0
count_room_guest                                                      1.0
count_room_kitchen                                                    1.0
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2021-11-19 18:00:09
date_updated                                          2021-11-19 17:44:45
source                                                             baania
url_unittype            https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
Name: 0, dtype: object)
จำนวนสมาชิก  2
สมาชิกตัวที่ 1 0
สมาชิกตัวที่ 2 row_number                                                          27501
unittype_id                                                 unittype_9565
project_id                                                   project_2446
name_th                                                         2 Bedroom
propertytype_id                                                         2
propertytype_name_en                                                Condo
propertytype_name_th                                                คอนโด
area_total_min_wa                                                     NaN
area_usable_min                                                      37.3
price_min                                                       2500000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  NaN
count_parking                                                         NaN
count_room_bath                                                       1.0
count_room_bed                                                        2.0
count_room_dinning                                                    1.0
count_room_guest                                                      1.0
count_room_kitchen                                                    1.0
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2021-11-19 18:00:09
date_updated                                          2021-11-19 17:44:45
source                                                             baania
url_unittype            https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
Name: 0, dtype: object
(1, row_number                                                          28777
unittype_id                                                unittype_10267
project_id                                                   project_3543
name_th                                                บ้านแฝดสองชั้น Z-2
propertytype_id                                                     20000
propertytype_name_en                                           Twin house
propertytype_name_th                                              บ้านแฝด
area_total_min_wa                                                    40.0
area_usable_min                                                     150.0
price_min                                                       2390000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  2.0
count_parking                                                         2.0
count_room_bath                                                       3.0
count_room_bed                                                        3.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2022-01-27 14:30:04
date_updated                                          2022-01-27 14:22:55
source                                                             baania
url_unittype            https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
Name: 1, dtype: object)
จำนวนสมาชิก  2
สมาชิกตัวที่ 1 1
สมาชิกตัวที่ 2 row_number                                                          28777
unittype_id                                                unittype_10267
project_id                                                   project_3543
name_th                                                บ้านแฝดสองชั้น Z-2
propertytype_id                                                     20000
propertytype_name_en                                           Twin house
propertytype_name_th                                              บ้านแฝด
area_total_min_wa                                                    40.0
area_usable_min                                                     150.0
price_min                                                       2390000.0
count_airconditioner                                                  NaN
count_elevator                                                        NaN
count_floor_internal                                                  2.0
count_parking                                                         2.0
count_room_bath                                                       3.0
count_room_bed                                                        3.0
count_room_dinning                                                    NaN
count_room_guest                                                      NaN
count_room_kitchen                                                    NaN
count_room_living                                                     NaN
count_room_maid                                                       NaN
count_room_storage                                                    NaN
count_room_utility                                                    NaN
date_created                                          2022-01-27 14:30:04
date_updated                                          2022-01-27 14:22:55
source                                                             baania
url_unittype            https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
Name: 1, dtype: object

## Groupby

In [31]:
unit.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...

In [32]:
unit.describe()

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
count,31772.000000,31772.000000,3136.000000,31772.000000,3.177200e+04,1334.000000,0.0,20946.000000,17100.000000,31117.000000,30880.000000,10938.000000,10048.000000,16010.000000,8053.000000,1539.000000,3416.000000,484.000000
mean,20742.017248,905.932425,44.084933,135.470846,5.812219e+06,2.446027,NaN,1.992361,1.854795,2.270881,2.453692,1.001646,1.010251,1.017114,1.050043,1.046784,1.050937,1.064050
std,12365.048954,4153.379976,21.600327,108.403541,1.164543e+07,1.519963,NaN,0.662424,0.760311,1.141710,1.186075,0.040535,0.103653,0.131138,0.250393,0.220284,0.250993,0.298424
min,1.000000,1.000000,1.000000,16.000000,1.000000e+05,1.000000,NaN,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,9498.750000,1.000000,22.675000,57.500000,1.990000e+06,1.000000,NaN,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,21481.500000,2.000000,50.000000,120.000000,3.211500e+06,2.000000,NaN,2.000000,2.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,31374.250000,3.000000,60.000000,175.000000,5.500000e+06,3.000000,NaN,2.000000,2.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,42625.000000,20000.000000,335.000000,4350.000000,5.800000e+08,10.000000,NaN,9.000000,10.000000,10.000000,10.000000,2.000000,3.000000,3.000000,5.000000,3.000000,4.000000,4.000000

In [33]:
unit.groupby(['propertytype_name_en']).mean() #ทุกค่าเป็น mean

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
propertytype_name_en,,,,,,,,,,,,,,,,,,
Apartment,14347.833333,5.0,NaN,32.000000,1.788333e+06,1.000000,NaN,NaN,NaN,1.000000,0.666667,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN
Commercial,21786.889575,4.0,22.938218,188.357583,4.512310e+06,2.545455,NaN,3.083075,1.710526,3.162111,2.871638,1.007874,1.006250,1.023041,1.094595,1.000000,1.045802,2.000000
Condo,20644.572843,2.0,NaN,61.315127,6.273014e+06,1.909091,NaN,2.082645,1.158228,1.373511,1.292853,1.000619,1.003828,1.002564,1.004291,1.061728,1.066667,1.000000
Detached House,20736.530514,1.0,55.266553,196.055752,7.094641e+06,3.085938,NaN,1.775630,2.010080,2.888992,3.226208,1.001943,1.014019,1.028525,1.111573,1.048423,1.047807,1.024691
Home office,22691.529644,6.0,28.565854,276.167470,1.079344e+07,5.000000,NaN,3.508000,2.844444,3.914980,2.718750,1.000000,1.044444,1.026316,1.208333,1.000000,1.062500,1.500000
Hotel,26764.500000,2362.0,NaN,57.750000,1.081375e+07,1.500000,NaN,NaN,NaN,1.000000,0.750000,1.000000,NaN,1.000000,1.000000,NaN,NaN,NaN
Office Space,35580.500000,7777.0,NaN,492.500000,1.825000e+07,NaN,NaN,4.000000,NaN,5.500000,4.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
Townhome,20561.698421,3.0,22.317826,128.617524,2.952449e+06,2.238739,NaN,2.158249,1.541206,2.395680,2.847408,1.001626,1.003754,1.008403,1.034514,1.000000,1.058383,1.081301
Twin house,20830.067596,20000.0,39.903211,139.504188,3.663223e+06,2.441860,NaN,1.846690,1.744628,2.454349,2.964106,1.003690,1.009600,1.025799,1.047847,1.050000,1.055276,1.076923
Warehouse / Factory,41127.800000,8.0,NaN,598.400000,1.840900e+07,NaN,NaN,2.400000,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
unit['propertytype_name_en'].unique() # ดูข้อมูลในคอลัมน์นั้นๆ

array(['Condo', 'Twin house', 'Townhome', 'Detached House', 'Commercial',
       'Home office', 'Hotel', 'Warehouse / Factory', 'Office Space',
       'Apartment'], dtype=object)

# HW2
1. เปรียบเทียบราคาเฉลี่ยของ Detached house, Condo, Twin house และ Townhome
2. พื้นที่ (area_total_min_wa และ area_usable_min) และ จำนวนห้องนอนของทรัพย์สินที่แพงที่สุดแต่ละชนิด
3. จำนวนที่จอดรถและห้องน้ำของของทรัพย์สินที่ถูกที่สุดแต่ละชนิด

##1.เปรียบเทียบราคาเฉลี่ยของ Detached house, Condo, Twin house และ Townhome

In [35]:
unit.head() # โชว์ข้อมูลตัวอย่างเพื่อแสดงว่าหัวตารางมีอะไรบ้าง

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...

In [36]:
unit.groupby(['propertytype_name_en'])['price_min'].mean()[['Detached House', 'Condo', 'Twin house', 'Townhome' ]]

propertytype_name_en
Detached House    7.094641e+06
Condo             6.273014e+06
Twin house        3.663223e+06
Townhome          2.952449e+06
Name: price_min, dtype: float64

### ของจาร

In [37]:
unit.groupby('propertytype_name_en')['price_min'].mean().reset_index() # ทำให้ตารางไม่เหลื่อม

  propertytype_name_en     price_min
0            Apartment  1.788333e+06
1           Commercial  4.512310e+06
2                Condo  6.273014e+06
3       Detached House  7.094641e+06
4          Home office  1.079344e+07
5                Hotel  1.081375e+07
6         Office Space  1.825000e+07
7             Townhome  2.952449e+06
8           Twin house  3.663223e+06
9  Warehouse / Factory  1.840900e+07

In [38]:
unit.groupby('propertytype_name_en').mean().reset_index() [['propertytype_name_en','price_min']]

  propertytype_name_en     price_min
0            Apartment  1.788333e+06
1           Commercial  4.512310e+06
2                Condo  6.273014e+06
3       Detached House  7.094641e+06
4          Home office  1.079344e+07
5                Hotel  1.081375e+07
6         Office Space  1.825000e+07
7             Townhome  2.952449e+06
8           Twin house  3.663223e+06
9  Warehouse / Factory  1.840900e+07

In [39]:
unit.groupby('propertytype_name_en').mean().reset_index() [['propertytype_name_en','price_min']]

  propertytype_name_en     price_min
0            Apartment  1.788333e+06
1           Commercial  4.512310e+06
2                Condo  6.273014e+06
3       Detached House  7.094641e+06
4          Home office  1.079344e+07
5                Hotel  1.081375e+07
6         Office Space  1.825000e+07
7             Townhome  2.952449e+06
8           Twin house  3.663223e+06
9  Warehouse / Factory  1.840900e+07

In [40]:
xx = unit.groupby('propertytype_name_en').mean().reset_index() [['propertytype_name_en','price_min']] [[False,False,True,True,False,False,False,True,True,False]]
xx                                                                                                                                                 # False ไม่เอา True เอา ex F อันแรก = ไม่เอาApartment

  propertytype_name_en     price_min
2                Condo  6.273014e+06
3       Detached House  7.094641e+06
7             Townhome  2.952449e+06
8           Twin house  3.663223e+06

In [41]:
XX = unit.groupby('propertytype_name_en').mean().reset_index()[['propertytype_name_en','price_min']]
XX[(XX['propertytype_name_en']=='Condo') | (XX['propertytype_name_en']=='Detached House') | (XX['propertytype_name_en']=='Townhome') | (XX['propertytype_name_en']=='Twin house')]

  propertytype_name_en     price_min
2                Condo  6.273014e+06
3       Detached House  7.094641e+06
7             Townhome  2.952449e+06
8           Twin house  3.663223e+06

## 2.พื้นที่ (area_total_min_wa และ area_usable_min) และ จำนวนห้องนอนของทรัพย์สินที่แพงที่สุดแต่ละชนิด

In [42]:
dm = unit.dropna(subset=['propertytype_name_en','price_min','area_total_min_wa','area_usable_min','count_room_bed','count_parking','count_room_bath','price_min']) # ลบ missing ออก

In [43]:
dm.groupby(['propertytype_name_en']).max()[['area_total_min_wa','area_usable_min','count_room_bed','price_min']]
 #Groupby ชนิดของบ้านแต่ละชนิด ใช้.max() หาค่าแพงที่สุด ใช้list เลือกเฉพาะ column พื้นที่และจำนวนห้องนอน

,area_total_min_wa,area_usable_min,count_room_bed,price_min
propertytype_name_en,,,,
Commercial,38.0,480.0,6.0,13600000.0
Detached House,100.0,850.0,7.0,110000000.0
Home office,66.0,640.0,5.0,32000000.0
Townhome,65.2,740.0,6.0,80000000.0
Twin house,96.5,330.0,5.0,18500000.0

### ของจาร

In [44]:
unit.groupby('propertytype_name_en') [['price_min','area_total_min_wa','area_usable_min','count_room_bed']].max()

,price_min,area_total_min_wa,area_usable_min,count_room_bed
propertytype_name_en,,,,
Apartment,2370000.0,NaN,40.00,1.0
Commercial,52000000.0,60.0,1360.00,10.0
Condo,580000000.0,NaN,4350.00,6.0
Detached House,285000000.0,335.0,2548.00,10.0
Home office,92000000.0,73.6,1065.00,10.0
Hotel,27300000.0,NaN,120.00,2.0
Office Space,25000000.0,NaN,585.00,4.0
Townhome,120000000.0,65.2,1000.00,10.0
Twin house,129000000.0,96.5,724.95,6.0
Warehouse / Factory,29200000.0,NaN,970.00,NaN

In [45]:
maxprice = unit.groupby('propertytype_name_en') [['price_min','area_total_min_wa','area_usable_min','count_room_bed']].max().reset_index()
maxprice

,propertytype_name_en,price_min,area_total_min_wa,area_usable_min,count_room_bed
0,Apartment,2370000.0,NaN,40.00,1.0
1,Commercial,52000000.0,60.0,1360.00,10.0
2,Condo,580000000.0,NaN,4350.00,6.0
3,Detached House,285000000.0,335.0,2548.00,10.0
4,Home office,92000000.0,73.6,1065.00,10.0
5,Hotel,27300000.0,NaN,120.00,2.0
6,Office Space,25000000.0,NaN,585.00,4.0
7,Townhome,120000000.0,65.2,1000.00,10.0
8,Twin house,129000000.0,96.5,724.95,6.0
9,Warehouse / Factory,29200000.0,NaN,970.00,NaN

In [46]:
for row in maxprice.iterrows():
    print(row[1]['propertytype_name_en'],row[1]['price_min'])
    print(unit[(unit['propertytype_name_en']==row[1]['propertytype_name_en']) & (unit['price_min']==row[1]['price_min'])][['area_total_min_wa','area_usable_min','count_room_bed']])

Apartment 2370000.0
       area_total_min_wa  area_usable_min  count_room_bed
36707                NaN             32.0             1.0
Commercial 52000000.0
       area_total_min_wa  area_usable_min  count_room_bed
10190                NaN           1065.0             7.0
Condo 580000000.0
       area_total_min_wa  area_usable_min  count_room_bed
33122                NaN           1182.0             3.0
Detached House 285000000.0
       area_total_min_wa  area_usable_min  count_room_bed
18443                NaN           2400.0             5.0
Home office 92000000.0
       area_total_min_wa  area_usable_min  count_room_bed
39868                NaN            856.0             NaN
Hotel 27300000.0
       area_total_min_wa  area_usable_min  count_room_bed
32899                NaN            120.0             2.0
Office Space 25000000.0
       area_total_min_wa  area_usable_min  count_room_bed
22348                NaN            585.0             NaN
Townhome 120000000.0
       area_total_min_wa  area_usable_min  count_room_bed
25460                NaN           1000.0             6.0
Twin house 129000000.0
       area_total_min_wa  area_usable_min  count_room_bed
26629                NaN           724.95             4.0
Warehouse / Factory 29200000.0
       area_total_min_wa  area_usable_min  count_room_bed
19424                NaN            970.0             NaN

ปริ้นค่าในแต่ละแถวของตาราง

In [47]:
unit[(unit['propertytype_name_en']==row[1]['propertytype_name_en']) & (unit['price_min']==row[1]['price_min'])][['area_total_min_wa','area_usable_min','count_room_bed']]

       area_total_min_wa  area_usable_min  count_room_bed
19424                NaN            970.0             NaN

##3.จำนวนที่จอดรถและห้องน้ำของของทรัพย์สินที่ถูกที่สุดแต่ละชนิด

In [48]:
dm.groupby(['propertytype_name_en']).min()[['count_parking','count_room_bath','price_min']]
 #Groupby ชนิดของบ้านแต่ละชนิด ใช้.min() หาค่าต่ำที่สุด ใช้list เลือกเฉพาะ column พื้นที่และจำนวนห้องนอน

                      count_parking  count_room_bath  price_min
propertytype_name_en
Commercial                      1.0              1.0  1690000.0
Detached House                  1.0              1.0   850000.0
Home office                     1.0              2.0  1990000.0
Townhome                        1.0              1.0   800000.0
Twin house                      1.0              1.0  1080000.0

### ของจาร

In [49]:
minprice = unit.groupby('propertytype_name_en') [['price_min','count_parking','count_room_bath']].min().reset_index()
minprice

  propertytype_name_en   price_min  count_parking  count_room_bath
0            Apartment   1390000.0            NaN              1.0
1           Commercial    468000.0            1.0              0.0
2                Condo    100000.0            1.0              0.0
3       Detached House    150000.0            1.0              0.0
4          Home office   1440500.0            1.0              0.0
5                Hotel   1390000.0            NaN              1.0
6         Office Space  11500000.0            NaN              5.0
7             Townhome    190000.0            1.0              0.0
8           Twin house    179000.0            1.0              0.0
9  Warehouse / Factory   7990000.0            NaN              0.0

In [50]:
for row in minprice.iterrows():
    print(row[1]['propertytype_name_en'],row[1]['price_min'])
    print(unit[(unit['propertytype_name_en']==row[1]['propertytype_name_en']) & (unit['price_min']==row[1]['price_min'])][['count_parking','count_room_bath']])

Apartment 1390000.0
       count_parking  count_room_bath
16700            NaN              1.0
Commercial 468000.0
      count_parking  count_room_bath
9006            NaN              0.0
Condo 100000.0
       count_parking  count_room_bath
8640             NaN              1.0
11019            NaN              1.0
17941            NaN              1.0
30364            NaN              1.0
Detached House 150000.0
      count_parking  count_room_bath
3729            NaN              1.0
Home office 1440500.0
       count_parking  count_room_bath
14390            3.0              3.0
Hotel 1390000.0
      count_parking  count_room_bath
3222            NaN              1.0
Office Space 11500000.0
      count_parking  count_room_bath
6454            NaN              6.0
Townhome 190000.0
       count_parking  count_room_bath
11036            NaN              2.0
Twin house 179000.0
      count_parking  count_room_bath
1133            2.0              1.0
Warehouse / Factory 7990000.0
       count_parking  count_room_bath
21711            NaN              0.0

In [51]:
unit[(unit['propertytype_name_en']==row[1]['propertytype_name_en']) & (unit['price_min']==row[1]['price_min'])][['count_parking','count_room_bath']]

       count_parking  count_room_bath
21711            NaN              0.0

# ต่อตาราง

## ต่อตารางแกน Y (เพิ่มปริมาณ ข้อมูล)

In [52]:
unit.shape

(31772, 27)

ตัดตารางออกเป็น 2 ส่วน

In [53]:
unitA = unit.iloc[:15000,:]
unitB = unit.iloc[15000:,:]

In [54]:
unitA.shape

(15000, 27)

In [55]:
unitB.shape

(16772, 27)

In [56]:
unitA.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...

In [57]:
unitB.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
20102,24339,unittype_14714,project_3315,2 Bedroom Floor 7-9,2,Condo,คอนโด,NaN,64.0,1825000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:50,2020-10-14 00:57:30,baania,https://baania.com/th/project/88-เดอะ-เทอมินอล...
20103,24163,unittype_19063,project_4702,1 Bedroom Floor 3-4,2,Condo,คอนโด,NaN,32.0,1067000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:21:15,2020-10-14 01:00:47,baania,https://baania.com/th/project/พายน์คอนโด-แจ้งว...
20104,7687,unittype_36239,project_15528,ลลิลพิณ,1,Detached House,บ้าน,NaN,180.0,4740000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:14,2020-09-17 14:37:27,baania,https://baania.com/th/project/ลลิล-อินเดอะพาร์...
20105,4561,unittype_30848,project_13004,Privilege,1,Detached House,บ้าน,NaN,446.7,22500000.0,...,1.0,2.0,1.0,NaN,1.0,1.0,2022-01-21 17:30:11,2022-01-21 17:21:54,baania,https://baania.com/th/project/ลัดดารมย์-อิลิแก...
20106,35133,unittype_33046,project_14094,1 Bedroom,2,Condo,คอนโด,NaN,28.0,2590000.0,...,NaN,1.0,1.0,NaN,NaN,NaN,2022-05-23 15:00:07,2022-05-23 14:47:09,baania,https://baania.com/th/project/เดอะคิวบ์-เออร์เ...

In [58]:
dataall = pd.concat([unitA,unitB]) # list ให้ความสำคัญกับลำดับ

In [59]:
dataall.shape

(31772, 27)

In [60]:
dataall.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...

In [61]:
pd.concat([unitB,unitA]).head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
20102,24339,unittype_14714,project_3315,2 Bedroom Floor 7-9,2,Condo,คอนโด,NaN,64.0,1825000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:20:50,2020-10-14 00:57:30,baania,https://baania.com/th/project/88-เดอะ-เทอมินอล...
20103,24163,unittype_19063,project_4702,1 Bedroom Floor 3-4,2,Condo,คอนโด,NaN,32.0,1067000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:21:15,2020-10-14 01:00:47,baania,https://baania.com/th/project/พายน์คอนโด-แจ้งว...
20104,7687,unittype_36239,project_15528,ลลิลพิณ,1,Detached House,บ้าน,NaN,180.0,4740000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:14,2020-09-17 14:37:27,baania,https://baania.com/th/project/ลลิล-อินเดอะพาร์...
20105,4561,unittype_30848,project_13004,Privilege,1,Detached House,บ้าน,NaN,446.7,22500000.0,...,1.0,2.0,1.0,NaN,1.0,1.0,2022-01-21 17:30:11,2022-01-21 17:21:54,baania,https://baania.com/th/project/ลัดดารมย์-อิลิแก...
20106,35133,unittype_33046,project_14094,1 Bedroom,2,Condo,คอนโด,NaN,28.0,2590000.0,...,NaN,1.0,1.0,NaN,NaN,NaN,2022-05-23 15:00:07,2022-05-23 14:47:09,baania,https://baania.com/th/project/เดอะคิวบ์-เออร์เ...

## ต่อตารางแกน  X (เพิ่มรายละเอียดของข้อมูล)

In [62]:
unit.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...

In [63]:
project = pd.read_csv('/content/drive/My Drive/BPDV65/opendata_project.csv')
project.head()

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...

In [64]:
unit.describe()

,row_number,propertytype_id,area_total_min_wa,area_usable_min,price_min,count_airconditioner,count_elevator,count_floor_internal,count_parking,count_room_bath,count_room_bed,count_room_dinning,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility
count,31772.000000,31772.000000,3136.000000,31772.000000,3.177200e+04,1334.000000,0.0,20946.000000,17100.000000,31117.000000,30880.000000,10938.000000,10048.000000,16010.000000,8053.000000,1539.000000,3416.000000,484.000000
mean,20742.017248,905.932425,44.084933,135.470846,5.812219e+06,2.446027,NaN,1.992361,1.854795,2.270881,2.453692,1.001646,1.010251,1.017114,1.050043,1.046784,1.050937,1.064050
std,12365.048954,4153.379976,21.600327,108.403541,1.164543e+07,1.519963,NaN,0.662424,0.760311,1.141710,1.186075,0.040535,0.103653,0.131138,0.250393,0.220284,0.250993,0.298424
min,1.000000,1.000000,1.000000,16.000000,1.000000e+05,1.000000,NaN,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,9498.750000,1.000000,22.675000,57.500000,1.990000e+06,1.000000,NaN,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,21481.500000,2.000000,50.000000,120.000000,3.211500e+06,2.000000,NaN,2.000000,2.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,31374.250000,3.000000,60.000000,175.000000,5.500000e+06,3.000000,NaN,2.000000,2.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,42625.000000,20000.000000,335.000000,4350.000000,5.800000e+08,10.000000,NaN,9.000000,10.000000,10.000000,10.000000,2.000000,3.000000,3.000000,5.000000,3.000000,4.000000,4.000000

### ต่อแบบเอาตารางมาต่อกันเลย

In [66]:
unit.merge(project)

ValueError: ignored

In [67]:
unit.merge(project, left_on='project_id', right_on='project_id')

,row_number_x,unittype_id,project_id,name_th_x,propertytype_id_x,propertytype_name_en_x,propertytype_name_th_x,area_total_min_wa,area_usable_min,price_min_x,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created_y,date_finish,date_updated_y,source_y,url_project
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,NaN,1.0,NaN,1.0,1.0,2016-11-10 16:56:40,2018-01-01 07:00:00,2021-11-19 18:00:09,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,38108,unittype_18502,project_2446,1 Bedroom,2,Condo,คอนโด,NaN,24.0,1390000.0,...,NaN,1.0,NaN,1.0,1.0,2016-11-10 16:56:40,2018-01-01 07:00:00,2021-11-19 18:00:09,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
2,2396,unittype_9564,project_2446,1 Bedroom Plus,2,Condo,คอนโด,NaN,29.0,1990000.0,...,NaN,1.0,NaN,1.0,1.0,2016-11-10 16:56:40,2018-01-01 07:00:00,2021-11-19 18:00:09,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
3,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,2017-01-24 13:55:45,2022-01-01 07:00:00,2022-01-27 14:30:04,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
4,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,2017-01-24 13:55:45,2022-01-01 07:00:00,2022-01-27 14:30:04,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39350,34220,unittype_34441,project_14828,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,120.0,5200000.0,...,NaN,1.0,NaN,1.0,1.0,2018-10-09 10:08:35,1970-01-02 07:00:00,2020-12-04 10:45:11,baania,https://baania.com/th/project/เอ็มเมอร์รัล-กรี...
39351,24384,unittype_14126,project_5602,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,349.0,18000000.0,...,NaN,NaN,NaN,NaN,1.0,2017-03-30 14:52:46,2006-01-26 07:00:00,2020-12-04 10:45:58,baania,https://baania.com/th/project/เดอะ-ซีนีธ-proje...
39352,33124,unittype_21700,project_8631,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,NaN,250.0,5990000.0,...,NaN,NaN,NaN,NaN,NaN,2017-07-11 15:26:09,1970-01-02 07:00:00,2020-12-04 10:46:14,baania,https://baania.com/th/project/พลอยไพลิน-เพลส-p...
39353,41022,617fc61e551dd10015a6933e,617fc4d3f62011001350de55,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,142.1,4880000.0,...,NaN,1.0,NaN,1.0,1.0,2021-11-01 17:43:31,NaN,2021-11-02 10:30:03,baania,https://baania.com/th/project/บ้านกลางเมือง-สุ...
39354,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,...,NaN,NaN,NaN,NaN,NaN,2019-07-12 15:47:44,1970-01-02 07:00:00,2020-12-04 10:42:26,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...

1. ราคาบ้านที่แพงที่สุดในจังหวัดขอนแก่น

In [68]:
this = unit.merge(project, left_on='project_id', right_on='project_id')
this[this['province_name_th']=='ขอนแก่น'].max()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

row_number_x                                                          42358
unittype_id                                                   unittype_9260
project_id                                                     project_3092
name_th_x                                                              ไทโซ
propertytype_id_x                                                     20000
propertytype_name_en_x                                           Twin house
propertytype_name_th_x                                            โฮมออฟฟิศ
area_total_min_wa                                                      90.0
area_usable_min                                                       609.0
price_min_x                                                      19580000.0
count_airconditioner                                                    5.0
count_elevator_x                                                        NaN
count_floor_internal                                                    9.0
count_parking_x                                                         5.0
count_room_bath                                                         7.0
count_room_bed                                                          6.0
count_room_dinning                                                      1.0
count_room_guest                                                        2.0
count_room_kitchen                                                      2.0
count_room_living                                                       2.0
count_room_maid                                                         1.0
count_room_storage                                                      3.0
count_room_utility                                                      1.0
date_created_x                                          2022-06-03 01:00:10
date_updated_x                                          2022-06-03 00:32:58
source_x                                                             baania
url_unittype              https://baania.com/th/project/ไฮด์-คอนโด-1909/...
row_number_y                                                        23279.0
name_en                                      ํํYoucharoen Baan Thum Phase 2
name_th_y                                                        ไฮด์ คอนโด
propertytype_id_y                                                         6
propertytype_name_en_y                                           Twin house
propertytype_name_th_y                                            โฮมออฟฟิศ
price_min_y                                                        990000.0
developer_id                                                 developer_9970
latitude                                                          16.862644
longitude                                                        103.084464
subdistrict_id                                                       2851.0
district_id                                                          2850.0
district_name_en                                                  WAENG NOI
district_name_th                                                    แวงน้อย
province_id                                                          2637.0
province_name_en                                                  Khon Kaen
province_name_th                                                    ขอนแก่น
zipcode                                                             40320.0
count_tower                                                            None
count_unit                                                            983.0
count_unittype                                                         15.0
facility_clubhouse                                                      1.0
facility_fitness                                                        1.0
facility_meeting                                                        1.0
facility_park                                                           1.0
facility_playground                                                     1.0
facility_pool                                                           1.0
facility_security                                                       1.0
date_created_y                                          2022-04-20 11:32:40
date_updated_y                                          2022-06-03 01:00:10
source_y                                                             baania
url_project               https://baania.com/th/project/ไฮด์-คอนโด-proje...
dtype: object

### ต่อแบบเลือกมาเฉพาะบาง column (map)

In [69]:
unit.merge(project, left_on='project_id', right_on='project_id')

,row_number_x,unittype_id,project_id,name_th_x,propertytype_id_x,propertytype_name_en_x,propertytype_name_th_x,area_total_min_wa,area_usable_min,price_min_x,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created_y,date_finish,date_updated_y,source_y,url_project
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,NaN,1.0,NaN,1.0,1.0,2016-11-10 16:56:40,2018-01-01 07:00:00,2021-11-19 18:00:09,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,38108,unittype_18502,project_2446,1 Bedroom,2,Condo,คอนโด,NaN,24.0,1390000.0,...,NaN,1.0,NaN,1.0,1.0,2016-11-10 16:56:40,2018-01-01 07:00:00,2021-11-19 18:00:09,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
2,2396,unittype_9564,project_2446,1 Bedroom Plus,2,Condo,คอนโด,NaN,29.0,1990000.0,...,NaN,1.0,NaN,1.0,1.0,2016-11-10 16:56:40,2018-01-01 07:00:00,2021-11-19 18:00:09,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
3,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,2017-01-24 13:55:45,2022-01-01 07:00:00,2022-01-27 14:30:04,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
4,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,2017-01-24 13:55:45,2022-01-01 07:00:00,2022-01-27 14:30:04,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39350,34220,unittype_34441,project_14828,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,120.0,5200000.0,...,NaN,1.0,NaN,1.0,1.0,2018-10-09 10:08:35,1970-01-02 07:00:00,2020-12-04 10:45:11,baania,https://baania.com/th/project/เอ็มเมอร์รัล-กรี...
39351,24384,unittype_14126,project_5602,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,349.0,18000000.0,...,NaN,NaN,NaN,NaN,1.0,2017-03-30 14:52:46,2006-01-26 07:00:00,2020-12-04 10:45:58,baania,https://baania.com/th/project/เดอะ-ซีนีธ-proje...
39352,33124,unittype_21700,project_8631,อาคารพาณิชย์สามชั้น,4,Commercial,อาคารพาณิชย์,NaN,250.0,5990000.0,...,NaN,NaN,NaN,NaN,NaN,2017-07-11 15:26:09,1970-01-02 07:00:00,2020-12-04 10:46:14,baania,https://baania.com/th/project/พลอยไพลิน-เพลส-p...
39353,41022,617fc61e551dd10015a6933e,617fc4d3f62011001350de55,ทาวน์โฮมสามชั้น,3,Townhome,ทาวน์โฮม,NaN,142.1,4880000.0,...,NaN,1.0,NaN,1.0,1.0,2021-11-01 17:43:31,NaN,2021-11-02 10:30:03,baania,https://baania.com/th/project/บ้านกลางเมือง-สุ...
39354,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,...,NaN,NaN,NaN,NaN,NaN,2019-07-12 15:47:44,1970-01-02 07:00:00,2020-12-04 10:42:26,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...

In [74]:
unit['project_id'].map(project.set_index('project_id')['price_min'])

InvalidIndexError: ignored

In [71]:
project_nodup = project.drop_duplicates(subset=['project_id'])

In [72]:
unit['pricemin'] = unit['project_id'].map(project_nodup.set_index('project_id')['price_min'])

In [73]:
unit.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,pricemin
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...,1390000.0
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...,1990000.0
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...,170000.0
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...,2390000.0
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...,9900000.0

# บันทึกตารางเป็นไฟล์

In [76]:
unit

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,pricemin
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...,1390000.0
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...,1990000.0
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...,170000.0
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...,2390000.0
5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,11700000.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...,9900000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42618,22299,unittype_13674,project_5356,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,130.0,36500000.0,...,NaN,1.0,NaN,NaN,NaN,2020-12-04 10:38:03,2020-10-14 00:47:50,baania,https://baania.com/th/project/บ้านศุธาวัลย์-53...,2500000.0
42619,11944,unittype_34884,project_15005,Ametrine,1,Detached House,บ้าน,NaN,353.0,23590000.0,...,1.0,1.0,1.0,1.0,NaN,2022-06-03 01:00:11,2022-06-03 00:51:19,baania,https://baania.com/th/project/เศรษฐสิริ-แจ้งวั...,15000000.0
42621,14,unittype_14016,project_5275,Grandeur,1,Detached House,บ้าน,NaN,223.0,7490000.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:36:32,2020-10-14 00:37:51,baania,https://baania.com/th/project/คาซ่า-วิลล์-ราชพ...,11500000.0
42623,9333,unittype_37375,project_16389,บ้านเดี่ยวชั้นเดียว,1,Detached House,บ้าน,NaN,180.0,3200000.0,...,1.0,NaN,NaN,NaN,NaN,2020-12-04 10:42:26,2020-10-14 19:30:46,baania,https://baania.com/th/project/ณรงค์กิจ-รามอินท...,3200000.0
42624,780,unittype_17011,project_6762,บ้านธารา,1,Detached House,บ้าน,NaN,170.0,3790000.0,...,1.0,NaN,NaN,NaN,NaN,2021-11-12 13:19:43,2020-10-14 00:41:39,baania,https://baania.com/th/project/วราสิริ-รังสิต-ด...,2490000.0

In [78]:
unit.to_csv('/content/drive/My Drive/BPDV65/myunit.csv')

In [82]:
#unit.to_excel('/content/drive/My Drive/BPDV65/myunit.xlsx')

In [83]:
unit.to_excel('/content/drive/My Drive/BPDV65/myunit.xlsx',sheet_name='unit1')

In [85]:
unit_from_excel = pd.read_excel('/content/drive/My Drive/BPDV65/myunit.xlsx',sheet_name='unit1')

In [93]:
unit_from_excel.head()

,Unnamed: 0,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,...,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype,pricemin
0,0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,...,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...,1390000.0
1,1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,...,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...,1990000.0
2,3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,...,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...,170000.0
3,4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,...,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...,2390000.0
4,5,30766,unittype_8026,project_2694,Luciano Grand,1,Detached House,บ้าน,70.5,198.0,...,NaN,NaN,NaN,NaN,NaN,2021-11-12 13:22:43,2020-10-14 19:35:20,baania,https://baania.com/th/project/คาซ่า-แกรนด์-ตาก...,9900000.0

# creat *ตาราง*

![creat ตาราง.jpg]()

## Dictionary-RowOriented

In [86]:
sales = [{'account' : 'Jones LLC','Jan' : 150,'Feb' : 200,'Mar' : 140},
            {'account' : 'Alpha Co','Jan' : 200,'Feb' : 210,'Mar' : 215},
            {'account' : 'Blue Inc','Jan' : 50,'Feb' : 90,'Mar' : 95}]

In [87]:
df = pd.DataFrame(sales)
df

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

## Dictionary-ColumnOriented

In [92]:
sales = {'account' : ['Jones LLC', 'Alpha Co', 'Blue Inc'],
            'Jan' : [150,200,140],
            'Feb' : [200,210,90],
            'Mar' : [140,215,95]}

In [94]:
df = pd.DataFrame.from_dict(sales)
df

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc  140   90   95

## List-RowOriented

In [91]:
sales = [['Jones LLC', 150, 200, 140],
            ['Alpha Co', 200, 210, 215],
            ['Blue Inc', 50, 90, 95]]
columnname = ['account','Jan','Feb','Mar']

In [95]:
df = pd.DataFrame.from_records(sales,columns=columnname)
df

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc  140   90   95